### ISSUE TITLE
Bump boot2docker distro to 1.8.1

### ISSUE THREAD

**Issue by runlevel5** [ailispaw/boot2docker-xhyve#10]
I hope that we could use the standard boot2docker distro (I am aware of the Parallel script issue)

**Comment by ailispaw** [comment]
Hi @joneslee85,
Thank you for opening this issue.

I hope so, too.
Unfortunately we can't use the standard boot2docker since Docker v1.7.1 because of Parallels.
I have already informed a Parallels guy of it.
https://github.com/ailispaw/boot2docker/pull/1#issuecomment-121845223

On the other hand, new docker/boot2docker could be used for this.
https://github.com/docker/boot2docker

Or you can use my docker-root distro instead of boot2docker.
https://github.com/ailispaw/docker-root-xhyve

Thanks.

**Comment by runlevel5** [comment]
@ailispaw what about applying patch on top of standard distro?

**Comment by ailispaw** [comment]
That's what I did for boot2docker v1.7.1.
https://github.com/ailispaw/boot2docker/commit/9a59e50c1e6df4b6e29ac82ebf67f912035308d6

But I don't want to follow boot2docker any more and I'm focusing on my docker-root project now.
I will wait for the standard boot2docker to support it or the new docker/boot2docker.
If anyone patches boot2docker anywhere, I'm willing to point it at that repository.

**Comment by runlevel5** [comment]
@ailispaw I mean to patch on-the-fly after downloading the standard ISO.

The docker/boot2docker looks nice though heavier than the TinyCore Linux based version. But for the sake of support, I'd vote for docker/boot2docker

**Comment by ailispaw** [comment]
@joneslee85 Oh, on-the-fly.
I don't know how to do that easily. Do you have any solution for it?

**Comment by runlevel5** [comment]
@ailispaw I'll have a look tonight for you

**Comment by ailispaw** [comment]
@joneslee85 Thanks. :)

**Comment by runlevel5** [comment]
@ailispaw I had a look, but no good. However, you could improve your forked boot2docker repo by only have a Dockefile that pull from official boot2docker/boot2docker docker hub registry and then use `patch` or whatever text editing tool to comment/remove part that disable Parallel
